# Generated by Django 4.1.5 on 2023-05-18 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=15, null=True)),
                ('last_name', models.TextField(max_length=15, null=True)),
                ('family', models.TextField(choices=[('Mithika', 'Mithika'), ('Kinoti', 'Kinoti'), ('Kalayu', 'Kalayu'), ('Kanini', 'Kanini'), ('Kimathi', 'Kimathi'), ('Karimi', 'Karimi'), ('Kalele', 'Kalele'), ('Kirito', 'Kirito')])),
                ('email', models.EmailField(help_text='Example: johndoe@gmail.com', max_length=50, null=True, unique=True)),
                ('phone_number', models.IntegerField(help_text='Example: 0700000000', null=True, unique=True)),
                ('birth_date', models.DateField(help_text='DD/MM/YYYY', null=True, unique_for_date=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
